### ISSUE TITLE
Patched kernel link down

### ISSUE THREAD

**Issue by ysangkok** [marcan/asbestos#2]
Hi. The link to ps3-linux is down. Do you know another place to get the required patches? Thanks in advance.

**Comment by marcan** [comment]
Andre Heider (a.heider@gmail.com) did the work to get support merged upstream, so the (woefully outdated) ps3-linux tree should no longer be needed. However, the approach used to pass the memory region info to the kernel is different from the original patches, so that requires a change in AsbestOS. I assume he has a patched version somewhere that supports the upstream kernel; I've never seen those patches myself, so you may want to ask him, or implement support yourself :-).

**Comment by ysangkok** [comment]
I wrote Andre an e-mail and he pointed me to http://repo.or.cz/asbestos.git . It includes the highmem patches.

**Comment by ysangkok** [comment]
Closing this since it isn't an issue with the actual code.
